--------------------------------------------------------
--  DDL for Table ANALYSIS_PROJECT_SRA_RUN_V2
--------------------------------------------------------

  CREATE TABLE "GOLD"."ANALYSIS_PROJECT_SRA_RUN_V2" 
   (	"ANALYSIS_PROJECT_ID" NUMBER, 
	"SRA_RUN_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
