--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "GOLD"."CONTACT" 
   (	"CONTACT_ID" NUMBER(16,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DEPARTMENT" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(255 BYTE), 
	"ORGANIZATION" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(1000 BYTE), 
	"CITY" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"ADD_DATE" DATE, 
	"X_SUPER_USER" VARCHAR2(10 BYTE) DEFAULT 'No', 
	"X_IMG_EDITOR" VARCHAR2(10 BYTE), 
	"X_IMG_GROUP" NUMBER(16,0), 
	"JGI_USER" VARCHAR2(20 BYTE), 
	"X_IMG_EDITING_LEVEL" VARCHAR2(2000 BYTE), 
	"CALIBAN_ID" NUMBER(*,0), 
	"CALIBAN_USER_NAME" VARCHAR2(512 BYTE), 
	"URL" VARCHAR2(2048 BYTE), 
	"X_IMG_CONTACT_ID" NUMBER(16,0), 
	"MASTER_CONTACT_ID" NUMBER(16,0), 
	"ORACLE_USER_NAME" VARCHAR2(50 BYTE), 
	"USER_ROLE" VARCHAR2(20 BYTE) DEFAULT 'User', 
	"GEBA_ORGANISM_AVAIL_COUNT" NUMBER, 
	"GEBA_REVIEWER" VARCHAR2(10 BYTE) DEFAULT 'No'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
