VOLUMEROOT=${VOLUMEROOT:-$(pwd)}

NEO4J_IMPORT_DIR=$VOLUMEROOT/oxo-neo4j-import
OLS_NEO4J_DATA=$VOLUMEROOT/ols-neo4j-data
ZOOMA_DATA=$VOLUMEROOT/zooma-data

rm -rfv "$NEO4J_IMPORT_DIR" "$OLS_NEO4J_DATA" "$ZOOMA_DATA"
